name: Saludo usando variables y secretos
on:
  workflow_dispatch:
env:
  DIA_DE_SEMANA: "Lunes"
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: "Hola"
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Hoy es ${{env.DIA_DE_SEMANA}}.!"
  saludo-secreto:
    runs-on: ubuntu-latest
    env:
      SALUDO: "Hola"
    steps:
      - name: Saludo secreto
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Tu contraseña es ${{secrets.CONTRASENA}}.!"
